spring:
  application:
    name: labs
  # Kafka ?????? KafkaProperties ???
  kafka:
    bootstrap-servers: 127.0.0.1:9092 # ?? Kafka Broker ???????????????
    # Kafka Producer ???
    producer:
      acks: 1 # 0-????1-leader ???all-?? leader ? follower ???
      retries: 3 # ?????????????
      key-serializer: org.apache.kafka.common.serialization.StringSerializer # ??? key ????
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer # ??? value ????
    # Kafka Consumer ???
    consumer:
      auto-offset-reset: earliest # ??????????????? earliest ?????? https://blog.csdn.net/lishuangzhe7047/article/details/74530417 ??
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      properties:
        spring:
          json:
            trusted:
              packages: com.demo.labs.message
    # Kafka Consumer Listener ?????
    listener:
      missing-topics-fatal: false # ????????????????????????????? false ?????

logging:
  level:
    org:
      springframework:
        kafka: ERROR # spring-kafka INFO ??????????????? ERROR ??
      apache:
        kafka: ERROR # kafka INFO ??????????????? ERROR ??